# encoding: utf-8
"""This file includes necessary params, info."""
import os
import mmcv
import os.path as osp

import numpy as np

# ---------------------------------------------------------------- #
# ROOT PATH INFO
# ---------------------------------------------------------------- #
cur_dir = osp.abspath(osp.dirname(__file__))
root_dir = osp.normpath(osp.join(cur_dir, ".."))
# directory storing experiment data (result, model checkpoints, etc).
output_dir = osp.join(root_dir, "output")

data_root = osp.join(root_dir, "datasets")

# ---------------------------------------------------------------- #
# NOCS DATASET
# ---------------------------------------------------------------- #
dataset_root = osp.join(data_root, "NOCS/")
train_dir = osp.join(dataset_root, "CAMERA/")

model_dir = osp.join(dataset_root, "obj_models")
mean_model_path = osp.join(model_dir, "cr_normed_mean_model_points_spd.pkl")
train_model_path = osp.join(model_dir, "camera_train.pkl")
test_model_path = osp.join(model_dir, "camera_val.pkl")

# object info
objects = ["bottle", "bowl", "camera", "can", "laptop", "mug"]

obj2id = {"bottle": 1, "bowl": 2, "camera": 3, "can": 4, "laptop": 5, "mug": 6}

obj_num = len(objects)

id2obj = {_id: _name for _name, _id in obj2id.items()}

# id2obj_camera = {1: "02876657", 2: "02880940", 3: "02942699", 4: "02946921", 5: "03642806", 6: "03797390"}
# objects_camera = list(id2obj_camera.values())
# obj2id_camera =  {_name: _id for _id, _name in id2obj_camera.items()}

# Camera info
width = 640
height = 480
center = (height / 2, width / 2)

intrinsics = np.array([[577.5, 0, 319.5], [0, 577.5, 239.5], [0, 0, 1]], dtype=np.float32)  # [fx, fy, cx, cy]

mean_scale = {
    "bottle": 0.001 * np.array([81, 218.5, 80.25], dtype=np.float32),
    "bowl": 0.001 * np.array([168.75, 67.75, 168.75], dtype=np.float32),
    "camera": 0.001 * np.array([116.0, 121.75, 175.5], dtype=np.float32),
    "can": 0.001 * np.array([112.5, 188.25, 115.0], dtype=np.float32),
    "laptop": 0.001 * np.array([145.25, 111.25, 168.0], dtype=np.float32),
    "mug": 0.001 * np.array([167.5, 135.0, 124.25], dtype=np.float32),
}


def get_mean_bbox3d():
    mean_bboxes = {}
    for key, value in intrinsics.items():
        minx, maxx = -value[0] / 2, value[0] / 2
        miny, maxy = -value[1] / 2, value[1] / 2
        minz, maxz = -value[2] / 2, value[2] / 2

        mean_bboxes[key] = np.array(
            [
                [maxx, maxy, maxz],
                [minx, maxy, maxz],
                [minx, miny, maxz],
                [maxx, miny, maxz],
                [maxx, maxy, minz],
                [minx, maxy, minz],
                [minx, miny, minz],
                [maxx, miny, minz],
            ],
            dtype=np.float32,
        )
    return mean_bboxes


def get_sym_info(obj_name, mug_handle=1):
    #  Y axis points upwards, x axis pass through the handle, z axis otherwise
    # return sym axis
    if obj_name == "bottle":
        sym = np.array([0, 1, 0], dtype=np.int)
    elif obj_name == "bowl":
        sym = np.array([0, 1, 0], dtype=np.int)
    elif obj_name == "camera":
        sym = None
    elif obj_name == "can":
        sym = np.array([0, 1, 0], dtype=np.int)
    elif obj_name == "laptop":
        sym = None
    elif obj_name == "mug":
        if mug_handle == 1:
            sym = None
        else:
            sym = np.array([0, 1, 0], dtype=np.int)
    else:
        raise NotImplementedError(f"No such a object class {obj_name}")
    return sym


def get_fps_points():
    """key is inst_name generated by
    core/catre/tools/nocs/nocs_fps_sample.py."""
    fps_points_path = osp.join(model_dir, "cmra_fps_points_spd.pkl")
    assert osp.exists(fps_points_path), fps_points_path
    fps_dict = mmcv.load(fps_points_path)
    return fps_dict
